import Link from 'next/link'

export default function Home() {
  return (
    <>
      <h1>Hey</h1>
      <p>« Ce Shakespeare est un esprit grossier et barbare, » dit lord Shaftesbury. Dryden ajoute : Shakespeare est inintelligible. Mistress Lennox donne à Shakespeare cette patoche : Ce poëte altère la vérité historique. Un critique allemand de 1680, Bentheim, se sent désarmé, parce que, dit-il, Shakespeare est une tête pleine de drôlerie. Ben Johnson, le protégé de Shakespeare, raconte lui-même ceci (ix, 175. Édition Gifford) : « Je me rappelle que les comédiens mentionnaient à l’honneur de Shakespeare que, dans ses écrits, il ne raturait jamais une ligne ; je répondis : Plût à Dieu qu’il en eût raturé mille ! » Ce vœu, du reste, fut exaucé par les honnêtes éditeurs de 1623, Blount et Jaggard. Ils retranchèrent, rien que dans Hamlet, deux cents lignes ; ils coupèrent deux cent vingt lignes dans le Roi Lear. Garrick ne jouait à Drury-Lane que le Roi Lear de Nahum Tate. Écoutons encore Rhymer : « Othello est une farce sanglante et sans sel. » Jonhson ajoute : « Jules César, tragédie froide et peu faite pour émouvoir. » « J’estime, dit Warburton dans sa lettre au doyen de Saint-Asaph, que Swift a bien plus d’esprit que Shakespeare et que le comique de Shakespeare, tout à fait bas, est bien inférieur au comique de Shadwell. » Quant aux sorcières de Macbeth, « rien n’égale, dit ce critique du dix-septième siècle, Forbes, répété par un critique du dix-neuvième, le ridicule d’un pareil spectacle. » Samuel Foote, l’auteur du Jeune Hypocrite, fait cette déclaration : « Le comique de Shakespeare est trop gros et ne fait pas rire. C’est de la bouffonnerie sans esprit. » Enfin, Pope, en 1725, trouve la raison pour laquelle Shakespeare a fait ses drames, et s’écrie : Il faut bien manger !</p>
      <p>Après ces paroles de Pope, on ne comprend guère à quel propos Voltaire, ahuri de Shakespeare, écrit : « Shakespeare, que les anglais prennent pour un Sophocle, florissait à peu près dans le temps de Lopez (Lope, s’il vous plaît, Voltaire) de Vega. » Voltaire ajoute : « Vous n’ignorez pas que dans Hamlet des fossoyeurs creusent une fosse en buvant, en chantant des vaudevilles, et en faisant sur les têtes des morts des plaisanteries convenables à gens de leur métier. » Et, concluant, il qualifie ainsi toute la scène : « Ces sottises ». Il caractérise les pièces de Shakespeare de ce mot : « Farces monstrueuses qu’on appelle tragédies », et complète le prononcé de l’arrêt en déclarant que Shakespeare « a perdu le théâtre anglais »</p>
    </>
  )
}
